version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - "< 3, >= 2.a"
  - dependency-name: io.sentry:sentry-logback
    versions:
    - 4.0.0
    - 4.1.0
    - 4.2.0
  - dependency-name: org.springframework.security:spring-security-test
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
