errors:
  - roman@proshin.org
alerts:
  suppress:
    - on-found-puzzle
    - on-lost-puzzle
    - on-scope
  github:
    - proshin-roman
format:
  - short-title
  - title-length=255
tags:
  - pdd
  - bug