language: java
sudo: false # faster builds
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
install: true
addons:
  sonarcloud:
    organization: "proshin-roman-github"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  app: $AWS_APP
  env: $AWS_ENV
  bucket_name: $AWS_BUCKET_NAME
  skip_cleanup: true
  on:
      branch: master
