language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
install: true
addons:
  sonarcloud:
    organization: proshin-roman-github
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
- mvn cobertura:cobertura
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: YTvlFmgnQNwdD8q+lEH+of2/TwK1jIBYGG1uBaf6RoobFjcFMAnqwyhhtZ2JcZ5l3h/2VhI5nYCSQl1tRBFx+XWCtlnEJRSmjAFE61Uvjr20UzNCrYtu5KpAgBH5ecV7ecYeRFn06Qszxl9L8haV7okuNzYrwXf1MrpoLHmvdj4MYWWr6HcgW3N4UTriHl5+Bkjz9KNV+VucmeVphdAkxuW2Q7MB7G4IaPvrSjTRjRFr06w1u1vTtgkXRfytzjSfj2HcQEWDanYKtVXAPSWxtQAmK35NFEQRbNos2ORWSI5aweqvYE5VTxNAQBTnp0wMOCC+E7RHMdwYlnFQLZbhF75yoVCg+VAiPfkHnNd865gRN7xxBYmS88HDwiH4RQSAX0AHPrNeTb/m18YCVYyvOVOjl14kzwyfmWe7tDFDZShIagkrD6d8FrA8qjCTVzKnEpAYUdVkCHEV3w4AjHozIVq3OjpbUkTbYMN8JezhFJ40eg61byTm9tXw33TddrzQmHoxq5bmt+FDXUsp6FXOXxX3e+BcYxBS0nTAbg76690WCnC4nPULj3tizKqNaBWisLy5VABxEAHiffDE0UhXlXhhgShi8pWjD60JApsUgnjLxjFAza0XjSUxQhlQbICYz8WPgmp6e2J5glHJxSB1Ce+ar15VRtUtUXedE+cByHY=
  app: proshin-org
  on:
    repo: proshin-roman/blog
