language: java
sudo: false # faster builds
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
install: true
addons:
  sonarcloud:
    organization: "proshin-roman-github"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
