spring:
  messages:
    fallback-to-system-locale: false
# blog:
  # admin:
    # username: you must specify it via System or Environment variables
    # password: you must specify it via System or Environment variables