spring:
  messages:
    fallback-to-system-locale: false
# blog:
  # admin:
    # username: you must specify it via System or Environment variables (required param)
    # password: you must specify it via System or Environment variables (required param)
  # dynamo:
    # region: you must specify it via System or Environment variables (required param)
    # endpoint: you can specify it via System or Environment variables (non-required param)
    # accessKey: you can specify it via System or Environment variables (non-required param)
    # secretKey: you can specify it via System or Environment variables (non-required param)